#!/usr/bin/env python3
"""Reduce an R script to a smaller xr2f compile-failure reproducer."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Trial:
    ok: bool
    returncode: int
    output: str


def split_top_level_blocks(src: str) -> list[str]:
    lines = src.splitlines(keepends=True)
    blocks: list[str] = []
    cur: list[str] = []
    depth = 0
    in_single = False
    in_double = False
    esc = False

    def scan_line(line: str) -> None:
        nonlocal depth, in_single, in_double, esc
        i = 0
        while i < len(line):
            ch = line[i]
            if esc:
                esc = False
                i += 1
                continue
            if ch == "\\":
                esc = True
                i += 1
                continue
            if ch == "'" and not in_double:
                in_single = not in_single
                i += 1
                continue
            if ch == '"' and not in_single:
                in_double = not in_double
                i += 1
                continue
            if not in_single and not in_double:
                if ch == "#":
                    break
                if ch in "([{":
                    depth += 1
                elif ch in ")]}":
                    depth = max(0, depth - 1)
            i += 1

    for line in lines:
        if not cur and not line.strip():
            blocks.append(line)
            continue
        cur.append(line)
        scan_line(line)
        if depth == 0 and not in_single and not in_double:
            blocks.append("".join(cur))
            cur = []
    if cur:
        blocks.append("".join(cur))
    return blocks


def run_cmd(cmd: list[str], cwd: Path, timeout: float) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as exc:
        out = (exc.stdout or "") + (exc.stderr or "")
        return subprocess.CompletedProcess(cmd, 124, out, "TIMEOUT\n")


def matches(output: str, patterns: list[str]) -> bool:
    return all(p in output for p in patterns)


def xr2f_compile_cmd(input_r: Path, out_f90: Path, args: argparse.Namespace) -> list[str]:
    cmd = [
        sys.executable,
        str(args.xr2f),
        str(input_r),
        "--out",
        str(out_f90),
        "--compile",
    ]
    if args.no_warn:
        cmd.append("--no-warn")
    return cmd


def infer_match_patterns(output: str) -> list[str]:
    patterns: list[str] = []
    compiler_error = ""
    for line in output.splitlines():
        m_err = re.search(r"\b(?:Error|Fatal Error):\s*(.+)$", line)
        if m_err is not None:
            compiler_error = m_err.group(1).strip()
            break
    if compiler_error:
        patterns.append(compiler_error)

    lines = output.splitlines()
    for i, line in enumerate(lines):
        if re.search(r"\.f90:\d+:\d+:", line):
            for cand in lines[i + 1 : i + 5]:
                m_sym = re.search(r"\b([A-Za-z][A-Za-z0-9_]{3,})\b", cand.strip())
                if m_sym and m_sym.group(1).lower() not in {"error", "warning", "real", "integer"}:
                    sym = m_sym.group(1)
                    if sym not in patterns:
                        patterns.append(sym)
                    return patterns
    return patterns


def infer_matches_from_original(in_path: Path, args: argparse.Namespace) -> tuple[list[str], str, int]:
    with tempfile.TemporaryDirectory(prefix="xr2f_reduce_probe_") as td:
        out_f90 = Path(td) / f"{in_path.stem}.f90"
        cmd = xr2f_compile_cmd(in_path, out_f90, args)
        proc = run_cmd(cmd, args.run_cwd, args.timeout)
        output = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode == 0:
        return [], output, proc.returncode
    return infer_match_patterns(output), output, proc.returncode


def write_candidate(path: Path, blocks: list[str], original_path: Path | None = None) -> None:
    banner = ""
    if original_path is not None:
        banner = f"# Generated by xr2f_reduce.py from {original_path}\n\n"
    text = banner + "".join(blocks)
    if text and not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")


_IDENT_RE = re.compile(r"\b[A-Za-z.][A-Za-z0-9_.]*\b")
_ASSIGN_RE = re.compile(r"(?m)^\s*([A-Za-z.][A-Za-z0-9_.]*)\s*(<-|=)([^\n]*)$")
_FOR_RE = re.compile(r"\bfor\s*\(\s*([A-Za-z.][A-Za-z0-9_.]*)\s+in\b")
_FUN_RE = re.compile(r"\bfunction\s*\(([^)]*)\)")

_R_WORDS = {
    "break",
    "else",
    "FALSE",
    "for",
    "function",
    "if",
    "in",
    "Inf",
    "NA",
    "NaN",
    "next",
    "NULL",
    "repeat",
    "return",
    "TRUE",
    "while",
}

_COMMON_BUILTINS = {
    "abs",
    "all",
    "any",
    "apply",
    "as.Date",
    "as.integer",
    "as.matrix",
    "as.numeric",
    "c",
    "cat",
    "colMeans",
    "colnames",
    "colSums",
    "data.frame",
    "diag",
    "diff",
    "dim",
    "drop",
    "exp",
    "file.exists",
    "floor",
    "ifelse",
    "is.finite",
    "length",
    "list",
    "log",
    "max",
    "mean",
    "min",
    "matrix",
    "ncol",
    "nrow",
    "options",
    "order",
    "paste",
    "print",
    "rbind",
    "read.csv",
    "rep",
    "return",
    "rownames",
    "rowMeans",
    "rowSums",
    "runif",
    "seq",
    "seq_along",
    "seq_len",
    "sqrt",
    "sum",
    "t",
    "which",
}


def _strip_r_strings_and_comments(text: str) -> str:
    out: list[str] = []
    in_single = False
    in_double = False
    esc = False
    i = 0
    while i < len(text):
        ch = text[i]
        if esc:
            out.append(" ")
            esc = False
            i += 1
            continue
        if ch == "\\" and (in_single or in_double):
            out.append(" ")
            esc = True
            i += 1
            continue
        if ch == "'" and not in_double:
            in_single = not in_single
            out.append(" ")
            i += 1
            continue
        if ch == '"' and not in_single:
            in_double = not in_double
            out.append(" ")
            i += 1
            continue
        if ch == "#" and not in_single and not in_double:
            while i < len(text) and text[i] != "\n":
                out.append(" ")
                i += 1
            continue
        out.append(" " if in_single or in_double else ch)
        i += 1
    return "".join(out)


def _assigned_names(block: str) -> set[str]:
    clean = _strip_r_strings_and_comments(block)
    names: set[str] = set()
    for name, op, rest in _ASSIGN_RE.findall(clean):
        if op == "=" and rest.rstrip().endswith(","):
            continue
        names.add(name)
    names.update(_FOR_RE.findall(clean))
    for match in _FUN_RE.finditer(clean):
        for arg in match.group(1).split(","):
            name = arg.split("=", 1)[0].strip()
            if _IDENT_RE.fullmatch(name or ""):
                names.add(name)
    return names


def _top_level_assigned_names(block: str) -> set[str]:
    clean = _strip_r_strings_and_comments(block)
    for line in clean.splitlines():
        if not line.strip():
            continue
        m = _ASSIGN_RE.match(line)
        if m is not None:
            name, op, rest = m.group(1), m.group(2), m.group(3)
            if op == "=" and rest.rstrip().endswith(","):
                return set()
            return {name}
        m_for = _FOR_RE.search(line)
        if m_for is not None:
            return {m_for.group(1)}
        return set()
    return set()


def _used_names(block: str) -> set[str]:
    clean = _strip_r_strings_and_comments(block)
    names = set(_IDENT_RE.findall(clean))
    return {name for name in names if name not in _R_WORDS and name not in _COMMON_BUILTINS}


def restore_dependency_blocks(candidate: list[str], all_blocks: list[str]) -> list[str]:
    """Keep simple top-level definitions needed by retained blocks.

    The reducer works on top-level blocks, so deleting an assignment used by a
    surviving loop or function call can create invalid R before xr2f sees it.
    This intentionally uses conservative text-level dependencies rather than a
    full R data-flow analysis.
    """

    selected = set(candidate)
    assign_blocks: dict[str, set[str]] = {}
    for block in all_blocks:
        for name in _top_level_assigned_names(block):
            assign_blocks.setdefault(name, set()).add(block)

    changed = True
    while changed:
        changed = False
        top_assigned = set()
        needed = set()
        for block in all_blocks:
            if block in selected:
                top_assigned.update(_top_level_assigned_names(block))
                needed.update(_used_names(block) - _assigned_names(block))
        for name in needed - top_assigned:
            for dep in assign_blocks.get(name, ()):
                if dep not in selected:
                    selected.add(dep)
                    changed = True

    return [block for block in all_blocks if block in selected]


def trim_overwritten_blocks(
    blocks: list[str],
    work_dir: Path,
    candidate_r: Path,
    candidate_f90: Path,
    args: argparse.Namespace,
) -> tuple[list[str], int]:
    """Try removing earlier top-level definitions shadowed by later definitions."""
    current = list(blocks)
    removed = 0
    i = 0
    while i < len(current):
        names = _top_level_assigned_names(current[i])
        if not names:
            i += 1
            continue
        later_names: set[str] = set()
        for later in current[i + 1 :]:
            later_names.update(_top_level_assigned_names(later))
        if not (names & later_names):
            i += 1
            continue
        candidate = current[:i] + current[i + 1 :]
        trial = check_candidate(candidate, work_dir, candidate_r, candidate_f90, args)
        if trial.ok:
            current = candidate
            removed += 1
            print(f"trimmed overwritten block: {len(current)} blocks")
            continue
        i += 1
    return current, removed


def trim_duplicate_definition_blocks(
    blocks: list[str],
    work_dir: Path,
    candidate_r: Path,
    candidate_f90: Path,
    args: argparse.Namespace,
) -> tuple[list[str], int]:
    """Try removing duplicate top-level definitions when another definition remains."""
    current = list(blocks)
    removed = 0
    i = len(current) - 1
    while i >= 0:
        names = _top_level_assigned_names(current[i])
        if not names:
            i -= 1
            continue
        other_names: set[str] = set()
        for j, block in enumerate(current):
            if j != i:
                other_names.update(_top_level_assigned_names(block))
        if not (names & other_names):
            i -= 1
            continue
        candidate = current[:i] + current[i + 1 :]
        trial = check_candidate(candidate, work_dir, candidate_r, candidate_f90, args)
        if trial.ok:
            current = candidate
            removed += 1
            print(f"trimmed duplicate definition: {len(current)} blocks")
            i = min(i, len(current) - 1)
            continue
        i -= 1
    return current, removed


def prune_restored_blocks(
    blocks: list[str],
    all_blocks: list[str],
    work_dir: Path,
    candidate_r: Path,
    candidate_f90: Path,
    args: argparse.Namespace,
) -> tuple[list[str], int]:
    """Try arbitrary removals after dependency restoration has re-expanded code."""
    current = list(blocks)
    removed = 0
    changed = True
    while changed:
        changed = False
        for i in range(len(current) - 1, -1, -1):
            raw_candidate = current[:i] + current[i + 1 :]
            if not raw_candidate:
                continue
            candidate = restore_dependency_blocks(raw_candidate, all_blocks)
            if current[i] in candidate:
                continue
            trial = check_candidate(candidate, work_dir, candidate_r, candidate_f90, args)
            if not trial.ok:
                continue
            current = candidate
            removed += 1
            changed = True
            print(f"pruned restored block: {len(current)} blocks")
            break
    return current, removed


def check_candidate(
    blocks: list[str],
    work_dir: Path,
    candidate_r: Path,
    candidate_f90: Path,
    args: argparse.Namespace,
) -> Trial:
    if getattr(args, "all_blocks", None):
        blocks = restore_dependency_blocks(blocks, args.all_blocks)
    write_candidate(candidate_r, blocks)
    if args.check_r:
        r_proc = run_cmd([args.rscript, str(candidate_r)], args.run_cwd, args.timeout)
        if r_proc.returncode != 0:
            return Trial(False, r_proc.returncode, (r_proc.stdout or "") + (r_proc.stderr or ""))
    cmd = xr2f_compile_cmd(candidate_r, candidate_f90, args)
    proc = run_cmd(cmd, args.run_cwd, args.timeout)
    output = (proc.stdout or "") + (proc.stderr or "")
    return Trial(proc.returncode != 0 and matches(output, args.match), proc.returncode, output)


def check_r_file(path: Path, args: argparse.Namespace) -> Trial:
    proc = run_cmd([args.rscript, str(path)], args.run_cwd, args.timeout)
    output = (proc.stdout or "") + (proc.stderr or "")
    return Trial(proc.returncode == 0, proc.returncode, output)


def ddmin_blocks(
    blocks: list[str],
    work_dir: Path,
    candidate_r: Path,
    candidate_f90: Path,
    args: argparse.Namespace,
) -> tuple[list[str], Trial]:
    current = list(blocks)
    last_trial = check_candidate(current, work_dir, candidate_r, candidate_f90, args)
    if not last_trial.ok:
        return current, last_trial
    args.successful_reductions = [list(current)]

    n = 2
    while len(current) >= 2:
        chunk = max(1, len(current) // n)
        reduced = False
        i = 0
        while i < len(current):
            candidate = current[:i] + current[i + chunk :]
            if not candidate:
                i += chunk
                continue
            trial = check_candidate(candidate, work_dir, candidate_r, candidate_f90, args)
            if trial.ok:
                current = candidate
                last_trial = trial
                args.successful_reductions.append(list(current))
                n = max(2, n - 1)
                reduced = True
                print(f"kept reduction: {len(current)} blocks")
                break
            i += chunk
        if not reduced:
            if n >= len(current):
                break
            n = min(len(current), n * 2)
    return current, last_trial


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Reduce an R script that triggers an xr2f compile failure")
    ap.add_argument("input_r", help="input R script")
    ap.add_argument(
        "--match",
        action="append",
        help=(
            "substring that must appear in xr2f compile output; repeat for multiple "
            "required substrings; default infers a signature from the original failure"
        ),
    )
    ap.add_argument("--out", help="reduced R output path (default: <input>_repro.r)")
    ap.add_argument("--out-f90", help="final generated Fortran path (default: <out stem>.f90)")
    ap.add_argument("--xr2f", default="xr2f.py", help="path to xr2f.py")
    ap.add_argument("--rscript", default="rscript", help="Rscript command used by --check-r")
    ap.add_argument(
        "--check-r",
        action="store_true",
        help="require each reduced candidate to run under Rscript",
    )
    ap.add_argument(
        "--check-r-final",
        action="store_true",
        help="run Rscript only on the final reduced R output",
    )
    ap.add_argument(
        "--backtrack",
        action="store_true",
        help=(
            "with --check-r-final, if the smallest repro fails under Rscript, "
            "emit the smallest earlier successful reduction that runs under R"
        ),
    )
    ap.add_argument(
        "--no-check-r",
        action="store_false",
        dest="check_r",
        help=argparse.SUPPRESS,
    )
    ap.add_argument("--run-cwd", default=".", help="working directory for xr2f/Rscript checks (default: current directory)")
    ap.add_argument("--timeout", type=float, default=60.0, help="per-candidate timeout in seconds")
    ap.add_argument("--no-warn", action="store_true", help="pass --no-warn to xr2f.py")
    args = ap.parse_args(argv)
    if args.backtrack and not args.check_r_final:
        print("--backtrack requires --check-r-final")
        return 2

    in_path = Path(args.input_r).resolve()
    args.xr2f = Path(args.xr2f).resolve()
    args.run_cwd = Path(args.run_cwd).resolve()
    if not in_path.exists():
        print(f"Missing input: {in_path}")
        return 2
    if not args.xr2f.exists():
        print(f"Missing xr2f.py: {args.xr2f}")
        return 2
    if not args.match:
        inferred, probe_output, probe_rc = infer_matches_from_original(in_path, args)
        if not inferred:
            print("Could not infer a compile-failure signature from the original input.")
            print(f"Initial xr2f exit code: {probe_rc}")
            print(probe_output)
            return 1
        args.match = inferred
        print("Inferred match substrings:")
        for pat in args.match:
            print(f"  {pat}")

    out_path = Path(args.out).resolve() if args.out else in_path.with_name(f"{in_path.stem}_repro.r")
    out_f90 = Path(args.out_f90).resolve() if args.out_f90 else out_path.with_suffix(".f90")
    src = in_path.read_text(encoding="utf-8-sig")
    blocks = split_top_level_blocks(src)
    if not blocks:
        print("No reducible blocks found.")
        return 1
    args.all_blocks = blocks

    with tempfile.TemporaryDirectory(prefix="xr2f_reduce_") as td:
        work_dir = Path(td)
        candidate_r = work_dir / in_path.name
        candidate_f90 = work_dir / f"{in_path.stem}.f90"
        reduced, trial = ddmin_blocks(blocks, work_dir, candidate_r, candidate_f90, args)
        if not trial.ok:
            print("Initial candidate did not reproduce requested failure.")
            print(trial.output)
            return 1
        reduced = restore_dependency_blocks(reduced, blocks)
        reduced, _trimmed = trim_overwritten_blocks(reduced, work_dir, candidate_r, candidate_f90, args)
        reduced, _dup_trimmed = trim_duplicate_definition_blocks(reduced, work_dir, candidate_r, candidate_f90, args)
        reduced, _pruned = prune_restored_blocks(reduced, blocks, work_dir, candidate_r, candidate_f90, args)
        reduced, _dup_trimmed = trim_duplicate_definition_blocks(reduced, work_dir, candidate_r, candidate_f90, args)
        final = check_candidate(reduced, work_dir, out_path, out_f90, args)
        if final.ok:
            write_candidate(out_path, reduced, in_path)
        print(f"wrote {out_path}")
        print(f"wrote {out_f90}")
        print(f"blocks: {len(blocks)} -> {len(reduced)}")
        if final.ok:
            if args.check_r_final:
                r_final = check_r_file(out_path, args)
                if r_final.ok:
                    print("R final check: PASS")
                    print("Reduce: PASS")
                    return 0
                if args.backtrack:
                    snapshots = getattr(args, "successful_reductions", [reduced])
                    seen: set[tuple[str, ...]] = set()
                    for snap in reversed(snapshots):
                        candidate_blocks = restore_dependency_blocks(snap, blocks)
                        candidate_blocks, _ = trim_overwritten_blocks(candidate_blocks, work_dir, candidate_r, candidate_f90, args)
                        candidate_blocks, _ = trim_duplicate_definition_blocks(candidate_blocks, work_dir, candidate_r, candidate_f90, args)
                        candidate_blocks, _ = prune_restored_blocks(candidate_blocks, blocks, work_dir, candidate_r, candidate_f90, args)
                        candidate_blocks, _ = trim_duplicate_definition_blocks(candidate_blocks, work_dir, candidate_r, candidate_f90, args)
                        key = tuple(candidate_blocks)
                        if key in seen:
                            continue
                        seen.add(key)
                        write_candidate(out_path, candidate_blocks, in_path)
                        r_trial = check_r_file(out_path, args)
                        if not r_trial.ok:
                            continue
                        compile_trial = check_candidate(candidate_blocks, work_dir, out_path, out_f90, args)
                        if not compile_trial.ok:
                            continue
                        write_candidate(out_path, candidate_blocks, in_path)
                        print(f"Backtrack: PASS ({len(candidate_blocks)} blocks)")
                        print("R final check: PASS")
                        print("Reduce: PASS")
                        return 0
                    write_candidate(out_path, reduced, in_path)
                    print("Backtrack: no earlier successful reduction passed Rscript.")
                print("R final check: FAIL")
                print(r_final.output)
                return 1
            print("Reduce: PASS")
            return 0
        print("Reduce: final repro check failed unexpectedly.")
        print(final.output)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
