xd <- c(10, 20, 30, 20, 40, 30)
print(xd)
print(duplicated(xd))
print(duplicated(xd, fromLast = TRUE))
print(anyDuplicated(xd))
xi = as.integer(xd)
print(xi)
print(duplicated(xi))
print(duplicated(xi, fromLast = TRUE))
print(anyDuplicated(xi))
xc = c("one", "two", "three", "two", "four", "three")
print(duplicated(xc))
print(duplicated(xc, fromLast = TRUE))
print(anyDuplicated(xc))
