xi = c(4L, 9L)
yi = 1:5
tf = is.element(xi, yi)
print(tf)
xr = c(4, 9)
yr = as.double(1:5)
tf = is.element(xr, yr)
print(tf)
xc = c("one", "two", "three")
yc = c("two", "four")
tf = is.element(xc, yc)
print(tf)
xb = c(TRUE, FALSE)
yb = c(TRUE)
tf = is.element(xb, yb)
print(tf)

