v <- c(3, 1, 4, 2)
vna <- c(3, NA, 4, 2)
d <- as.double(v)
m <- rbind(c(1, 2, 3), c(4, 5, 6), c(7, 8, 9), c(10, 11, 12))
ch <- character(3)
rw <- raw(4)
shaped <- 1:6
dim(shaped) <- c(2, 3)

cat("prod:", prod(v), "\n")
cat("prod na:", prod(vna, na.rm = TRUE), "\n")
cat("as double:", d, "\n")
cat("rev:", rev(v), "\n")
cat("which max:", which.max(v), "\n")
cat("which min:", which.min(v), "\n")
cat("rep int:", rep.int(2, 4), "\n")
cat("rep int vec:", rep.int(c(1, 2), c(2, 3)), "\n")
cat("dim:", dim(m), "\n")
cat("dim assign:", shaped[2, 3], "\n")
cat("character len:", length(ch), "\n")
cat("raw len:", length(rw), "\n")
cat("drop row:", drop(m[1, ]), "\n")
cat("drop col:", drop(m[, 2]), "\n")
cat("mod:", Mod(-3), "\n")
cat("re:", Re(3), "\n")
cat("im:", Im(3), "\n")
cat("conj:", Conj(3), "\n")
cat("arg neg:", Arg(-3), "\n")
