xi = c(2L,4L,6L)
yi = c(1L,4L,9L)
print(union(xi, yi))
print(intersect(xi, yi))
print(setdiff(xi, yi))
print(setdiff(yi, xi))
print(setequal(xi, yi))
xr = c(2,4,6)
yr = c(1,4,9)
print(union(xr, yr))
print(intersect(xr, yr))
print(setdiff(xr, yr))
print(setdiff(yr, xr))
print(setequal(xr, yr))
xc = c("two", "four", "six")
yc = c("one", "four", "nine")
print(union(xc, yc))
print(intersect(xc, yc))
print(setdiff(xc, yc))
print(setdiff(yc, xc))
print(setequal(xc, yc))
